name = "my-honox-blog"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"
compatibility_date = "2024-05-13"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "honox"
database_id = "a8ce7af9-af7f-4e54-8f2e-c25e3d9a1cd6"
